---
- name: Copy file with owner and permissions
  copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present

- name: Add GPG keys.
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://packagecloud.io/gpg.key"
    - "https://packagecloud.io/rabbitmq/erlang/gpgkey"
    - "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
    - "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc"

- name: Ensure erlang is installed.
  package:
    name: "{{ item }}"
    state: present  
  with_items:
    - erlang 
    - rabbitmq-server

- name: Add firewalld rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 15672/tcp
    - 5672/tcp
    - 4369/tcp
    - 25672/tcp
  notify: Reload firewalld
  when: rabbit_firewall
